modLoader = "kotlinforforge"
loaderVersion = "[3,)"
issueTrackerURL = "https://github.com/RPMTW/RPMTW-Platform-Mod/issues"
license = "GPL 3"

[[mods]]
modId = "rpmtw_platform_mod"
version = "${version}"
displayName = "RPMTW Platform Mod"
authors = "SiongSng, watermelon_1024, Yuta Yamamoto"
description = '''
整合了RPMTW各項服務的模組，涵蓋翻譯、百科、宇宙通訊、中文輸入優化等功能，讓 Minecraft 中文玩家獲得更好的遊戲體驗。

The mod integrated with RPMTW services covers translation, wiki, cosmic chat, Chinese input optimization, and other features for Minecraft players to get a better gaming experience.'''
logoFile = "rpmtw-platform-logo.png"

[[dependencies.rpmtw_platform_mod]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rpmtw_platform_mod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rpmtw_platform_mod]]
modId = "architectury"
mandatory = true
versionRange = "[4.0.29,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.rpmtw_platform_mod]]
modId = "cloth_config"
mandatory = true
versionRange = "[6.2,)"
ordering = "NONE"
side = "BOTH"